run_name: 'APPLE dataset | Mean condition on D | Mean of G | Relativistic GAN loss | Shuffle on data'

system:
  batch_size: 10
  seq_len: 150
  learning_rate: 1e-4
  num_epochs: 100
  device: 'cuda:1'

d:
  d_num_layers: 1
  d_dim_hidden: 16
  d_dim_input: 1
  d_iter: 16

g:
  g_num_layers: 1
  g_dim_hidden: 128
  g_dim_latent: 128
  g_dim_output: 1
  g_iter: 1

