system:
  batch_size: 10
  seq_len: 150
  learning_rate: 1e-4
  num_epochs: 100
  device: 'cuda:0'
  num_samples: 100
  run_name: 'G mean + std condition'
  dataset: ''
  datasets: ['electricity', 'taxi', 'solar', 'traffic', 'exchange']
  model: 'rcgan'

d:
  d_num_layers: 1
  d_dim_hidden: 32
  d_dim_input: 1
  d_iter: 16

g:
  g_num_layers: 1
  g_dim_hidden: 64
  g_dim_latent: 128
  g_dim_output: 1
  g_iter: 1

